### ISSUE TITLE
Not a issue, Just a request

### ISSUE THREAD

**Issue by Rownak** [GreenTechBd/Al-Quran-Tafsir-by-Word-#2]
Assalamu Alaikum,

All the apps developed by your team is so good and very user friendly, MashAllah. I appreciate your volunteer efforts for creating such important materials available to billions of people all over the world. May Allah bless all of you.

I have a request to add some extra features to **_organize the bookmarks_**. I usually use the bookmarks in the A-Quran app as labels. For example, All the verses that describe the afterlife are bookmarked by label "Akhirah", so that when I want to remind myself about the afterlife I can go to the bookmark and read all the verses related to it. Currently, I finished only 2 Juzz and I marked around 80+ bookmarks. Hence, it becomes difficult to search bookmark and sometimes I have multiple bookmarks with similar tags. Particularly, when bookmarking a new verse, go through previous bookmarks is much time-consuming. Could you please provide **_a search option and a serial number option with the bookmarks_**? Also, **_a moving option to change the order of the bookmarks_** will be a great help. Thank you for your patience.

<img width="414" alt="Screenshot 2020-05-16 at 2 32 08 PM" src="https://user-images.githubusercontent.com/7727454/82127875-c08a7c80-9784-11ea-8038-d977e2419db4.png">

**Comment by GreenTechBd** [comment]
Assalamu 'alaikum wa rahmatullahi wa barakatuh dear Brother!

JazakAllahu khairan for your beautiful suggestion brother.


   -

   *Bookmark Search: *Can be done in future in sha Allah
   -

   *Bookmark Serial Number:* Can you share more details brother, how do you
   feel serial number is important? We want to know more.

Finally, we have our public issue tracker at gitlab.

I have created an issue for request:
https://gitlab.com/greentech/quran/quran-android/-/issues/599


If you have further suggestions, feel free to create issues in our Gitlab
Issue tracker. We have issue trackers for all apps in gitlab.


Keep us in your duas. May Allah accept good deeds of all of us, and forgive
the shortcomings.


BarakAllahu feekum


Best regards,

Download & Support Our Apps: gtaf.org

**Comment by Rownak** [comment]
JazakAllah Khair for your quick response.
